### ISSUE TITLE
export function?

### ISSUE THREAD

**Issue by stanstrup** [rformassspectrometry/MsBackendMsp#6]
Is there any plans for an export function?
The most straight forward reference I could find is this: https://rdrr.io/cran/OrgMassSpecR/man/WriteMspFile.html

**Comment by michaelwitting** [comment]
Yes, should be doable. I would suggest to follow the example of `MsBackendMassbank` or `MsBackendMgf` using the version with the mapping of the spectra variables

**Comment by michaelwitting** [comment]
I just added a prototype to my branch `devel_michael`.
Here is some code to test it:

```
library(MsBackendMsp)

fls <- dir(system.file("extdata", package = "MsBackendMsp"),
           full.names = TRUE, pattern = "msp$")
be <- MsBackendMsp()

res1 <- backendInitialize(be, fls[1])

export(Spectra(res1), backend = MsBackendMsp(), file = "test.msp")
```

**Comment by michaelwitting** [comment]
We might need to finish our collection on the different .msp styles we started in Wittenberg

**Comment by stanstrup** [comment]
Thanks! This is great and seems to work.

Some comments and suggestions:
* According to the [NIST specs (Page 10)](https://chemdata.nist.gov/mass-spc/ftp/mass-spc/PepLib.pdf) the mz and intensity should be tab delimited. Now they are space delimited. MoNa is using space delimited files too so I guess it is fine.
* The specs also mention peak annotation which would be very nice. I have an example spectra object here with annotation data for each peak: https://github.com/rformassspectrometry/MsBackendMgf/issues/4#issuecomment-701316475.
* The comment field seems to be used to fill in all arbitrary data and would also be nice to be able to use.
* Would it be possible to allow arbitrary fields to be added íf they are specified in the mapping? Only mz/intensity/annotation should require special formatting I guess.

Example MoNa msp:
```
Name: Sulfamethoxazole
Synon: 4-amino-N-(5-methyl-1,2-oxazol-3-yl)benzenesulfonamide
Synon: $:00in-source
DB#: AU101851
InChIKey: JLKIGFTWXXRPMT-UHFFFAOYSA-N
Precursor_type: [M-H]-
Spectrum_type: MS2
PrecursorMZ: 252.0448
Instrument_type: LC-ESI-QTOF
Instrument: Bruker maXis Impact
Ion_mode: N
Collision_energy: 10 eV
Formula: C10H11N3O3S
MW: 253
ExactMass: 253.05211221199997
Comments: "SMILES=CC1=CC(NS(=O)(=O)C2=CC=C(N)C=C2)=NO1" "cas=723-46-6" "chebi=9332" "pubchem cid=5329" "chemspider=5138" "InChI=InChI=1S/C10H11N3O3S/c1-7-6-10(12-16-7)13-17(14,15)9-4-2-8(11)3-5-9/h2-6H,11H2,1H3,(H,12,13)" "computed SMILES=CC1=CC(=NO1)NS(=O)(=O)C2=CC=C(C=C2)N" "accession=AU101851" "date=2016.02.27" "author=Nikiforos Alygizakis, Nikolaos Thomaidis, University of Athens" "license=CC BY" "copyright=Copyright (C) 2016 Department of Chemistry, University of Athens" "comment=CONFIDENCE standard compound" "comment=INTERNAL_ID 1018" "exact mass=253.0521122" "ionization=ESI" "fragmentation mode=CID" "resolution=35000" "column=Acclaim RSLC C18 2.2um, 2.1x100mm, Thermo" "flow gradient=99/1 at 0-1 min, 61/39 at 3 min, 0.1/99.9 at 14-16 min, 99/1 at 16.1-20 min" "flow rate=200 uL/min at 0-3 min, 400 uL/min at 14 min, 480 uL/min at 16-19 min, 200 uL/min at 19.1-20 min" "retention time=3.276 min" "SOLVENT A=90:10 water:methanol with 5mM ammonium acetate" "SOLVENT B=methanol with 5mM ammonium acetate" "recalibrate=identity on assigned fragments and MS1" "whole=RMassBank 1.99.10" "computed mass accuracy=0.14367287073283105" "computed mass error=-3.621199996928226E-5" "SPLASH=splash10-0a4i-0940000000-88c5b1ef2f503737ca9a" "submitter=Nikolaos Thomaidis (University of Athens)" "MoNA Rating=4.375"
Num Peaks: 2
156.0178 100.000000
252.0506 49.545455
```

Currently implemented fields:
* [X] Name:
* [ ] Synon: (multiple allowed)
* [X] DB#:
* [X] InChIKey: 
* [ ] Precursor_type: 
* [ ] Spectrum_type: 
* [X] PrecursorMZ: 
* [ ] Instrument_type: 
* [ ] Instrument: 
* [ ] Ion_mode: 
* [ ] Collision_energy: 
* [X] Formula: 
* [ ] MW: 
* [X] ExactMass: 
* [X] RETENTIONTIME:
* [ ] Comments:

**Comment by michaelwitting** [comment]
Certainly doable. I envision actually to have mappings for the different styles of .msp already encoded in the package. Maybe with @jo_rainer we can check the different styles and mappings? Would be interesting for `CompoundDB` as well since we agreed on some standards names there already.

**Comment by stanstrup** [comment]
I have reached the point where I need this for my standard curation GUI. So you are not working on this right now, right?

Some questions:
1. Why are you removing these columns? https://github.com/sneumann/MsBackendMsp/blob/7e3ac2f1d911e731d7a885c1db52bac2542f9527/R/functions-msp.R#L164
  `dataOrigin` is just a character.
2. What is the current flavor of msp fields implemented?
3. I would like to implement the MoNa flavour.
 a. Should we treat synonyms as any other field and require the multi-line to be build into the input string with `\nSynon: `?
4. How do you feel about the peak annotation described in the specs? I haven't seen it in the wild but something like that would be useful.


Btw.: Do you currently see a more proper format for a compound database? Msp seem to be the most mainstream but is crazy if you have to stuff all the info into the comment field.

**Comment by michaelwitting** [comment]
Hi @stanstrup ,

sorry I have been busy the other days. There is no current flavor, everything a bit wildstyle ad the moment. Generally, I'm not a big fan of msp (as you said everything is in comment fields, which I really don't like). However, it is the major format for most of the software. From my side feel free to implement what you need. I guess @sneumann also has no problem with it.

Best,

Michael

**Comment by jorainer** [comment]
Update: I'm about to fix the export to support mapping of additional fields and handling multiple Synon: fields (issue #9 )
