### ISSUE TITLE
Support for different version of .msp

### ISSUE THREAD

**Issue by michaelwitting** [rformassspectrometry/MsBackendMsp#7]
Different version of .msp exsit. For example MoNA stores the information on the adduct in `Precursor_type`, while MSDial uses a field `PRECURSORTYPE`.
Solution is the implementation of `spectraVariableMapping` similar to the MsBackendMgf

**Comment by jorainer** [comment]
That's now implemented in https://github.com/rformassspectrometry/MsBackendMsp/commit/f39ff9137e71f1c3d9300fa4e2c97eb355c456f0
